version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9-buster
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Hello World"